/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AddProuctView': RouteRecordInfo<'/AddProuctView', '/AddProuctView', Record<never, never>, Record<never, never>>,
    '/AdminProfileView': RouteRecordInfo<'/AdminProfileView', '/AdminProfileView', Record<never, never>, Record<never, never>>,
    '/EditProductView': RouteRecordInfo<'/EditProductView', '/EditProductView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/ProductDetailView': RouteRecordInfo<'/ProductDetailView', '/ProductDetailView', Record<never, never>, Record<never, never>>,
    '/ProductsView': RouteRecordInfo<'/ProductsView', '/ProductsView', Record<never, never>, Record<never, never>>,
    '/RegisterView': RouteRecordInfo<'/RegisterView', '/RegisterView', Record<never, never>, Record<never, never>>,
    '/UserProfileView': RouteRecordInfo<'/UserProfileView', '/UserProfileView', Record<never, never>, Record<never, never>>,
  }
}
